style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/antonbabenko/pre-commit-terraform
options:
  header:
    pattern: "^(.*)$"
    pattern_maps:
      - Subject
